title: CS-499 Computer Science Capstone
description: SNHU GitHub Pages site for Rick Goshen's senior capstone project.
theme: minima

# Build settings
markdown: kramdown

# Exclude from processing
exclude:
  - README.md
